services:
  - type: web
    name: e_commerce-app
    runtime: python
    buildCommand: poetry install
    startCommand: |
      poetry run python manage.py migrate
      poetry run python manage.py collectstatic --noinput
      poetry run python manage.py runserver 0.0.0.0:8000
