# Generated by Django 4.2.21 on 2025-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_rename_categoty_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
